// Rebuilds the two generated files behind the hero window (website/app/):
//
//   app/app.css  the app's own stylesheets, copied unchanged and joined in the
//                order the app loads them, so the hero is drawn by the same
//                rules as the real window and cannot drift from it.
//   app/orb.js   the orb animation the app uses (the thinking-orbs package,
//                MIT), bundled for a plain page.
//
// Run from the repo root after the app's styles change:  node website/sync-app.mjs

import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { build } from "esbuild";

const here = dirname(fileURLToPath(import.meta.url));
const src = join(here, "..", "src");

// Same order as src/main.tsx first, then each component's sheet.
const SHEETS = [
  "styles/tokens.css",
  "styles/global.css",
  "styles/menu.css",
  "App.css",
  "components/TopBar/TopBar.css",
  "components/TopBar/TabStrip.css",
  "components/Rail/Rail.css",
  "components/EngineStatus/EngineStatus.css",
  "components/Mark/Mark.css",
  "routes/Chat.css",
  "components/Conversation/Conversation.css",
  "components/Context/Context.css",
  "components/Memory/Memory.css",
  "components/Composer/Composer.css",
  "components/Composer/EffortPicker.css",
  "components/Composer/ContextMeter.css",
  "components/ModelPicker/ModelPicker.css",
  "components/Workbench/Workbench.css",
];

const css = SHEETS.map((f) => `/* ---- ${f} ---- */\n${readFileSync(join(src, f), "utf8")}`).join("\n\n");
writeFileSync(
  join(here, "app", "app.css"),
  `/* GENERATED by website/sync-app.mjs from the app's own stylesheets. Do not edit. */\n\n${css}\n`
);

await build({
  entryPoints: [join(here, "app", "orb-entry.js")],
  outfile: join(here, "app", "orb.js"),
  bundle: true,
  minify: true,
  format: "iife",
  target: "es2020",
  banner: { js: "/* thinking-orbs (MIT), bundled by website/sync-app.mjs */" },
});

console.log("website/app/app.css and website/app/orb.js written");
